#image: mwienk/docker-git-ftp
#deploy_all: FTP_deploy
#  stage: deploy
#  script:
#    - apt-get update -qq && apt-get install -y -qq lftp
#    - git config git-ftp.url $FTP_HOST
#    - git config git-ftp.password $FTP_PASSWORD
#    - git config git-ftp.user $FTP_NAME
#    - git ftp init
#    #- git ftp push  -m "Add new content"
#  only:
#    - master


image: ubuntu:18.04
before_script:
  - apt-get update -qy
  - apt-get install -y lftp
build:
  script:
    - lftp -e "open $FTP_HOST; user $FTP_USERNAME $FTP_PASSWORD; mirror -X .* -X .*/ --reverse --verbose --delete local-folder/ destination-folder/; bye"